### ISSUE TITLE
申请Bangumi.cyou邮箱转发

### ISSUE THREAD

**Issue by in-dexter** [everything-cyou/bangumidotcyou#1]
### 自定义地址

p1stach@bangumi.cyou

### 转发到的邮箱

gu1p@foxmail.com

### 你是一位 Bangumi 用户吗？

![截屏图片](https://user-images.githubusercontent.com/106669046/189533989-7b574045-4d1b-4820-9ae7-86dd003ea770.jpg)
你好！请问我需要把账号截出来吗？ (bgm38)

### 服务条款

- [x] 我知道了

**Comment by RealLanta** [comment]
通过审核，已创建

**Comment by RealLanta** [comment]
Cloudflare已向您的邮箱([gu1p@foxmail.com](mailto:gu1p@foxmail.com))发送一封验证邮件，确认后即刻生效

**Comment by in-dexter** [comment]
好的，感谢！
