### ISSUE TITLE
邮箱转发申请

### ISSUE THREAD

**Issue by teteko233** [everything-cyou/bangumidotcyou#3]
### 自定义地址

teteko@bangumi.cyou

### 转发到的邮箱

teteko233@gmail,com

### 你是一位 Bangumi 用户吗？

![image.png](https://pic7.58cdn.com.cn/nowater/webim/big/n_v2867033d00e824f21b954c94e322d9b6a.png)

### 服务条款

- [ ] 我知道了

**Comment by RealLanta** [comment]
通过
Cloudflare已向您的邮箱([teteko233@gmail.com](mailto:teteko233@gmail.com))发送一封验证邮件，确认后即刻生效
