### ISSUE TITLE
申请子域名

### ISSUE THREAD

**Issue by MoonCC233** [everything-cyou/bangumidotcyou#5]
### 网站名字

Niute Fony

### 公开我的域名？

- [X] 公开

### 您想要什么前缀？

niute.bangumi.cyou

### 解析类型

CNAME

### 解析内容

Niufuyu855.github.io

### 你需要开启 Cloudflare CDN 吗？

n

### 你是一位 Bangumi 用户吗？

是是是！
![image](https://user-images.githubusercontent.com/103884299/194497557-38d52ba0-1269-453d-9673-2dc82317cd77.png)

### 警告

- [X] 我知道了

**Comment by RealLanta** [comment]
pass
