### ISSUE TITLE
邮箱转发申请

### ISSUE THREAD

**Issue by MoonCC233** [everything-cyou/bangumidotcyou#6]
### 自定义地址

niute@bangumi.cyou

### 转发到的邮箱

3327223191@qq.com

### 你是一位 Bangumi 用户吗？

啊对对对！
啊是是是！
你是海外华侨嘛？
这么帅！
我要上 ```Lanta之声``` ！
![image](https://user-images.githubusercontent.com/103884299/194502041-80beff0d-f77c-41b1-a677-c703a7239fe2.png)

### 服务条款

- [X] 我知道了

**Comment by RealLanta** [comment]
通过
Cloudflare已向您的邮箱[3327223191@qq.com](mailto:3327223191@qq.com)发送一封验证邮件，确认后即刻生效
