### ISSUE TITLE
Izumi Chino's Blog

### ISSUE THREAD

**Issue by IzumiChino** [everything-cyou/bangumidotcyou#7]
### 网站名字

Izumi Chino's Blog

### 公开我的域名？

- [X] 公开

### 您想要什么前缀？

izumichino

### 解析类型

CNAME

### 解析内容

1.1.1.1

### 你需要开启 Cloudflare CDN 吗？

yes

### 你是一位 Bangumi 用户吗？

![image](https://user-images.githubusercontent.com/122081822/211180300-f4e41c8e-71b7-4098-9a7d-fc7e28dce02c.png)

### 警告

- [X] 我知道了

**Comment by RealLanta** [comment]
您好，1.1.1.1仅作为示范（1.1.1.1为Cloudflare所属IP），并且CNAME也不能解析IP地址

**Comment by IzumiChino** [comment]
> 

那能否帮我配置，谢谢

**Comment by RealLanta** [comment]
用户已更改请求，通过
