### ISSUE TITLE
申请邮箱转发

### ISSUE THREAD

**Issue by IzumiChino** [everything-cyou/bangumidotcyou#8]
### 自定义地址

izumichino@bangumi.cyou

### 转发到的邮箱

因为部分原因不显示

### 你是一位 Bangumi 用户吗？

![image](https://user-images.githubusercontent.com/122081822/211180288-9b9b437c-70f4-44ef-b600-e5dee7795f69.png)

### 服务条款

- [X] 我知道了

**Comment by RealLanta** [comment]
通过
Cloudflare已向您的邮箱[2156786315@qq.com](mailto:2156786315@qq.com)发送一封验证邮件，确认后即刻生效
