### ISSUE TITLE
关于我

### ISSUE THREAD

**Issue by yftdtddh** [everything-cyou/bangumidotcyou#9]
### 网站名字

关于我

### 公开我的域名？

- [x] 公开

### 您想要什么前缀？

muxiyuj

### 解析类型

CNAME

### 解析内容

https://muxiyujyyuj.github.io/

### 你需要开启 Cloudflare CDN 吗？

n

### 你是一位 Bangumi 用户吗？

[https://p.sda1.dev/10/1fee1f590e15913cc0d3b71280102604/Screenshot_2023-03-21-18-33-54-73.jpg](url)

### 警告

- [X] 我知道了

**Comment by RealLanta** [comment]
Pass
